app:
  name: jim_gateway
  ver: 1.0.1
  env: local
websocket:
  host: 127.0.0.1
  port: 9000
  log: log/websocket.log
tcp:
  host: 127.0.0.1
  port: 9001
  log: log/tcp.log
rpc:
  host: 127.0.0.1 #0.0.0.0
  port: 9093
  ttl: 5
  log: log/rpc.log

jaeger:
  host: 127.0.0.1 #172.17.0.1
  port: 6831

pubsub:
  brokers:
    - "127.0.0.1:9092"
gateway:
  id: 1

runtime:
  mode : local #kafka grpc